before_script:
    - sudo apt-get update -qq
    - sudo apt-get install -qq doxygen
    - sudo apt-get install -qq libboost1.48-dev
    - sudo apt-get install -qq libboost1.48-test-dev
    - export BOOST_ROOT=/usr
language: cpp
script: cd build && cmake .. && make && make test
