function(printlist PREFIX L)
    foreach (ITEM ${L})
        message(STATUS "${PREFIX}${ITEM}")
    endforeach()
endfunction()

macro(printtarget HEADERS SOURCES LIBS)
    message(STATUS "        Headers:")
    printlist("            " "${HEADERS}")
    message(STATUS "        Sources:")
    printlist("            " "${SOURCES}")
    message(STATUS "        Libraries:")
    printlist("            " "${LIBS}")
endmacro()

macro(set_target NAME)
    set(TARGET_NAME "${NAME}")
    set(TARGET_BUILD TRUE)
    message(STATUS "==== ${TARGET_NAME} ====")
endmacro()

macro(build_if CONDITION FAIL_REASON)
    if (TARGET_BUILD)
        if (NOT ${CONDITION})
            message(STATUS "NOT Building \"${TARGET_NAME}\" because: ${FAIL_REASON}.")
            set(TARGET_BUILD FALSE)
        endif()
    endif()
endmacro()


# UTIL_ASSERT(TEST COMMENT_FAIL [COMMENT_PASS=''] [IS_FATAL=FALSE])
macro(UTIL_ASSERT TEST COMMENT_FAIL)
    if (${TEST})
        # ARG2 holds COMMENT_PASS
        if (${ARGC} GREATER 2)
            message(STATUS ${ARGV2})
        endif()
    else()
        set(IS_FATAL 0)
        if (${ARGC} GREATER 3)
            set(IS_FATAL ${ARGV3})
        endif()

        if (${IS_FATAL})
            message(FATAL_ERROR ${COMMENT_FAIL})
        else()
            message(STATUS ${COMMENT_FAIL})
        endif()
    endif()
endmacro()
