set(CMAKE_MODULE_PATH "${PROJECT_CMAKE_DIR}")

message(STATUS "CMAKE_MODULE_PATH:")
printlist("    " "${CMAKE_MODULE_PATH}")

set(PROJECT_BIN_DIR "${CMAKE_CURRENT_BINARY_DIR}/bin")
set(PROJECT_LIB_DIR "${CMAKE_CURRENT_BINARY_DIR}/lib")
set(PROJECT_ARCHIVE_DIR "${CMAKE_CURRENT_BINARY_DIR}/lib")

set(PROJECT_ETC_DIR "${PROJECT_SOURCE_DIR}/etc")

set(DOXYGEN_DOCUMENTATION_DIR "${PROJECT_BINARY_DIR}/doxygen")
set(DOXYGEN_DOCUMENTATION_LAYOUT_DIR "${DOXYGEN_DOCUMENTATION_DIR}/layout")
set(DOXYGEN_DOCUMENTATION_HTML_OUTPUT_DIR_REL "html")

set(DOXYGEN_DOCUMENTATION_PAGES_DIR "${PROJECT_ETC_DIR}/doxygen/pages")
set(DOXYGEN_DOCUMENTATION_SNIPPET_DIR "${PROJECT_ETC_DIR}/doxygen/snippets")
set(DOXYGEN_DOCUMENTATION_IMAGE_DIR "${PROJECT_ETC_DIR}/doxygen/images")
